import 'package:hatonet_hcn/app/model/list_job.dart';

final FAKE_LIST_JOB = [
  ListJob(
    company: ' Devwork JSC',
    status: ' Chưa nộp hồ sơ',
    money: '50-80',
    city: ' Hồ Chí Minh',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Lập kế hoạch test, xây dựng kịch bản test cho các sản phẩm Web, Mobile app, API ...',
    day: '2',
    checkimage:'' ,
    tittle: 'Senior Android Engineer (Java - Kotlin)',
    date: '4',
    image: 'assets/icons/ic_circle_tick.svg',
    firtskillname: '',
    skillname: 'Fullstack',
  ),
  ListJob(
    checkimage:'' ,
    company: ' Hachinet JSC',
    status: ' Đã nộp hồ sơ',
    money: '150-280',
    city: ' Hà Nội',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Tham gia thiết kế và viết các tài liệu thiết kế chi tiết (SAD, SDD, Screen Design)',
    day: '24',
    tittle: 'Senior IOS Engineer (Objective-C)',
    date: '10',
    image: 'assets/icons/ic_green_circle_tick.svg',
    firtskillname: '',
    skillname: 'Fullstack',
  ),
  ListJob(
    checkimage:'' ,
    company: ' Devwork JSC',
    status: ' Chưa nộp hồ sơ',
    money: '50-80',
    city: ' Hồ Chí Minh',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Lập kế hoạch test, xây dựng kịch bản test cho các sản phẩm Web, Mobile app, API ...',
    day: '2',
    tittle: 'Senior Android Engineer (Java - Kotlin)',
    date: '4',
    image: 'assets/icons/ic_circle_tick.svg',
    firtskillname: '',
    skillname: 'Fullstack',
  ),
  ListJob(
    checkimage:'' ,
    company: ' Hachinet JSC',
    status: ' Đã nộp hồ sơ',
    money: '150-280',
    city: ' Hà Nội',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Tham gia thiết kế và viết các tài liệu thiết kế chi tiết (SAD, SDD, Screen Design)',
    day: '24',
    tittle: 'Senior IOS Engineer (Objective-C)',
    date: '10',
    image: 'assets/icons/ic_green_circle_tick.svg',
    firtskillname: '',
    skillname: 'Fullstack',
  ),
];
