import 'package:hatonet_hcn/app/model/tittle_list_job.dart';
final FAKE_TITTLE_LIST_JOB = [
  TittleListJob(
    company: ' Devwork JSC',
    status: ' Chưa nộp hồ sơ',
    money: '50 - 80',
    city: ' Hồ Chí Minh',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Lập kế hoạch test, xây dựng kịch bản test cho các sản phẩm Web, Mobile app, API ...',
    day: '0',
    avatar: 'assets/images/logo hatonet-06.png',
    time: 'Thời gian nộp đã hết',
    checkimage:'assets/icons/ic_simple_icon_time.svg' ,
    tittle: 'Senior Android Engineer (Java - Kotlin)',
    date: '4',
    companyimage: 'assets/icons/ic_simple_calendar.svg',
    image: 'assets/icons/ic_circle_tick.svg',
    firtskillname: 'Icons.access_time_outlined',
    skillname: 'Fullstack',
  ),
  TittleListJob(
    checkimage:'' ,
    company: ' Hachinet JSC',
    status: ' Đã nộp hồ sơ',
    money: '1 - 8',
    time: '',
    avatar: 'assets/images/logo hatonet-06.png',
    city: ' Hà Nội',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Tham gia thiết kế và viết các tài liệu thiết kế chi tiết (SAD, SDD, Screen Design)',
    day: '24',
    tittle: 'Senior IOS Engineer (Objective-C)',
    date: '10',
    image: 'assets/icons/ic_green_circle_tick.svg',
    firtskillname: '',
    companyimage: 'assets/icons/ic_simple_calendar.svg',
    skillname: 'Fullstack',
  ),
  TittleListJob(
    checkimage:'' ,
    company: ' Hachinet JSC',
    status: ' Đã nộp hồ sơ',
    money: '1 - 8',
    time: '',
    avatar: 'assets/images/logo hatonet-06.png',
    city: ' Hà Nội',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Tham gia thiết kế và viết các tài liệu thiết kế chi tiết (SAD, SDD, Screen Design)',
    day: '24',
    tittle: 'Senior IOS Engineer (Objective-C)',
    date: '10',
    image: 'assets/icons/ic_green_circle_tick.svg',
    firtskillname: '',
    companyimage: 'assets/icons/ic_simple_calendar.svg',
    skillname: 'Fullstack',
  ),
  TittleListJob(
    checkimage:'' ,
    company: ' Hachinet JSC',
    status: ' Đã nộp hồ sơ',
    money: '1 - 8',
    time: '',
    avatar: 'assets/images/logo hatonet-06.png',
    city: ' Hà Nội',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Tham gia thiết kế và viết các tài liệu thiết kế chi tiết (SAD, SDD, Screen Design)',
    day: '24',
    tittle: 'Senior IOS Engineer (Objective-C)',
    date: '10',
    image: 'assets/icons/ic_green_circle_tick.svg',
    firtskillname: '',
    companyimage: 'assets/icons/ic_simple_calendar.svg',
    skillname: 'Fullstack',
  ),
  TittleListJob(
    checkimage:'' ,
    time: '',
    avatar: 'assets/images/logo hatonet-06.png',
    company: ' Devwork JSC',
    status: ' Chưa nộp hồ sơ',
    money: '50 - 80',
    city: ' Hồ Chí Minh',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Lập kế hoạch test, xây dựng kịch bản test cho các sản phẩm Web, Mobile app, API ...',
    day: '2',
    companyimage: 'assets/icons/ic_simple_calendar.svg',
    tittle: 'Senior Android Engineer (Java - Kotlin)',
    date: '4',
    image: 'assets/icons/ic_circle_tick.svg',
    firtskillname: '',
    skillname: 'Fullstack',
  ),
];
