import 'package:hatonet_hcn/app/model/list_item_box_page_two.dart';

final FAKE_BOX_PAGE_TWO_LIST_JOB = [
  ListItemPageBoxJob(
    company: ' Devwork JSC',
    status: ' Chưa nộp hồ sơ',
    money: '50 - 80',
    city: ' Hồ Chí Minh',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Lập kế hoạch test, xây dựng kịch bản test cho các sản phẩm Web, Mobile app, API ...',
    day: '0',
    time: 'Thời gian nộp đã hết',
    checkimage:'assets/icons/ic_simple_icon_time.svg' ,
    tittle: 'Senior Android Engineer (Java - Kotlin)',
    date: '4',
    image: 'assets/icons/ic_circle_tick.svg',
    firtskillname: 'Icons.access_time_outlined',
    skillname: 'Fullstack',
  ),
  ListItemPageBoxJob(
    company: ' Devwork JSC',
    status: ' Chưa nộp hồ sơ',
    money: '50 - 80',
    city: ' Hồ Chí Minh',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Lập kế hoạch test, xây dựng kịch bản test cho các sản phẩm Web, Mobile app, API ...',
    day: '0',
    time: 'Thời gian nộp đã hết',
    checkimage:'assets/icons/ic_simple_icon_time.svg' ,
    tittle: 'Senior Android Engineer (Java - Kotlin)',
    date: '4',
    image: 'assets/icons/ic_circle_tick.svg',
    firtskillname: 'Icons.access_time_outlined',
    skillname: 'Fullstack',
  ),
  ListItemPageBoxJob(
    checkimage:'' ,
    company: ' Hachinet JSC',
    status: ' Đã nộp hồ sơ',
    money: '1 - 8',
    time: '',
    city: ' Hà Nội',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Tham gia thiết kế và viết các tài liệu thiết kế chi tiết (SAD, SDD, Screen Design)',
    day: '24',
    tittle: 'Senior IOS Engineer (Objective-C)',
    date: '10',
    image: 'assets/icons/ic_green_circle_tick.svg',
    firtskillname: '',
    skillname: 'Fullstack',
  ),
  ListItemPageBoxJob(
    checkimage:'' ,
    time: '',
    company: ' Devwork JSC',
    status: ' Chưa nộp hồ sơ',
    money: '50 - 80',
    city: ' Hồ Chí Minh',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Lập kế hoạch test, xây dựng kịch bản test cho các sản phẩm Web, Mobile app, API ...',
    day: '2',
    tittle: 'Senior Android Engineer (Java - Kotlin)',
    date: '4',
    image: 'assets/icons/ic_circle_tick.svg',
    firtskillname: '',
    skillname: 'Fullstack',
  ),
  ListItemPageBoxJob(
    checkimage:'' ,
    time: '',
    company: ' Hachinet JSC',
    status: ' Đã nộp hồ sơ',
    money: '150 - 280',
    city: ' Hà Nội',
    deatailjob: 'Đọc hiểu, phân tích tài liệu đặc tả yêu cầu người sử dụng và tài liệu phân tích thiết kế hệ thống. Tham gia thiết kế và viết các tài liệu thiết kế chi tiết (SAD, SDD, Screen Design)',
    day: '24',
    tittle: 'Senior IOS Engineer (Objective-C)',
    date: '10',
    image: 'assets/icons/ic_green_circle_tick.svg',
    firtskillname: '',
    skillname: 'Fullstack',
  ),
];